version: '3'
services:
        jupyter:
                depends_on: 
                        - redis
                image: marcolorusso/jupyreview
                environment:
                        - JUPYTER_ENABLE_LAB=yes
                        - JUPYTER_TOKEN="asd"
                        - CHOWN_HOME=yes
                        - CHOWN_HOME_OPTS="-R"
                networks:
                        - bdp2-net
                ports:
                        - 80:8888
                user: root
                volumes:
                        - ~/review/BDP2-Review/work:/home/jovyan

        redis:
                image: redis
                networks:
                        - bdp2-net
                user: "1000"
                volumes:
                        - ~/review/BDP2-Review/work:/data
                command:
                        - redis-server
        portainer:
                image: portainer/portainer-ce
                networks:
                        - bdp2-net
                ports:
                        - 8000:8000
                        - 443:9443
                restart: always
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - portainer_data:/data



volumes:
        portainer_data:
networks:
        bdp2-net:
