name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build docker/ --file docker/Dockerfile --tag marcolorusso/jupyreview:$(date +%s)
    - name: Push the image to DockerHub
      run: docker login -u marcolorusso -p ${{ secrets.DOCKER_TOKEN }} && docker push marcolorusso/jupyreview:$(date +%s)
